image: Visual Studio 2017

build_script:
        - ps: "cd ..\\..; move projects\\DotNetPELib .; cd DotNetPELib; .\\ms; cd ..; move DotNetPELib projects"

artifacts:
  - path: "Release\\DotNetPELib.lib"
    name: DotNetPELib
  - path: "Release\\NetLink.exe"
    name: NetLink
  - path: "DotNetPELib.h"
    name: Header File